"""Generate Python source code from the steps tree.

The code of a step is written, then the code of its children.  The
children continue at the indentation where the step's code ends, one level
deeper after a ``:`` (``if``, ``for``, ``def`` ...), and ``pass`` is added
when a block has nothing to run.  Disabled steps are written as comments.
"""

INDENT = "    "
TOP_LEVEL_BLOCKS = ("def ", "class ", "async def ", "@", 'if __name__ ==')


class Output:
    def __init__(self):
        self.lines = []
        self.owners = []     # step id for each line

    def emit(self, text, step):
        self.lines.append(text)
        self.owners.append(step.id)


def generate(project, header=True):
    """Return ``(source, owners)``; ``owners[n]`` is the id of the step that
    wrote line ``n + 1``."""
    out = Output()
    if header:
        out.emit("# Generated by PWCT-Python (Programming Without Coding Technology)", project.root)
        out.emit("# Project: %s" % project.name, project.root)
        out.emit("", project.root)
    imports = collect_imports(project.root)
    for line, step in imports:
        out.emit(line, step)
    if imports:
        out.emit("", project.root)
    _write_children(project.root, 0, False, out)
    return "\n".join(out.lines) + "\n", out.owners


def import_line(name):
    name = name.strip()
    if name.startswith(("import ", "from ")):
        return name
    return "import " + name


def collect_imports(root):
    """The import lines needed by the enabled steps, in order, without
    duplicates: ``[(line, step)]``."""
    seen, result = set(), []

    def visit(step):
        if step.disabled:
            return
        for name in step.imports:
            line = import_line(name)
            if line not in seen:
                seen.add(line)
                result.append((line, step))
        for child in step.children:
            visit(child)

    visit(root)
    return result


def _write_children(step, level, commented, out):
    runnable = False
    for child in step.children:
        runnable |= _write(child, level, commented or child.disabled, out)
    return runnable


def _write(step, level, commented, out):
    if level == 0 and step.code and step.code[0].startswith(TOP_LEVEL_BLOCKS):
        if out.lines and out.lines[-1].strip():
            out.emit("", step)   # a blank line before top level definitions
    prefix = INDENT * level + ("# " if commented else "")
    runnable = False
    for line in step.code:
        out.emit(prefix + line, step)
        if not commented and not line.strip().startswith("#"):
            runnable = True
    child_level = level + step.child_indent
    inner = _write_children(step, child_level, commented, out)
    if step.is_block and not inner and not commented:
        out.emit(INDENT * child_level + "pass", step)
    return runnable or inner


def step_at_line(owners, lineno):
    """The step id that owns a (1 based) line number."""
    if 1 <= lineno <= len(owners):
        return owners[lineno - 1]
    return None
